--- name:default
# the network port to use for the vicon tracking system
server_port: 5000
# from frame for the transformer
source_frame: "body" # transformer names. No transformation convention
# to frame for the transformer
target_frame: "world_osg" # transformer names. No transformation convention
# the network port to use for the vicon tracking system
data_port: 5000
# the network host of the ART tracking system
host: '131.176.25.107'

--- name:exoter
# the number of the body that is being tracked
numBody: 3

# transformation between segment cs (vicon data)and a choosen body fixed reference cs
body_reference:
  time:
    microseconds: 0
  sourceFrame: 'body_art'
  targetFrame: 'selected_marker'
  position:
    data:
    - 0.0
    - 0.0
    - 0.0
  cov_position:
    data:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  orientation:
    im:
    - 0.0
    - 0.0
    - 0.0
    re: 0.0
  cov_orientation:
    data:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  velocity:
    data:
    - 0.0
    - 0.0
    - 0.0
  cov_velocity:
    data:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  angular_velocity:
    data:
    - 0.0
    - 0.0
    - 0.0
  cov_angular_velocity:
    data:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
# set the origin of the segment, includes position and orientation.
origin:
  time:
    microseconds: 0
  sourceFrame: 'art'
  targetFrame: 'body'
  position:
    data:
    - 5.0
    - 1.0
    - 0.5
  cov_position:
    data:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  orientation:
    im:
    - 0.0
    - 0.0
    - 0.0
    re: 0.0
  cov_orientation:
    data:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  velocity:
    data:
    - 0.0
    - 0.0
    - 0.0
  cov_velocity:
    data:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  angular_velocity:
    data:
    - 0.0
    - 0.0
    - 0.0
  cov_angular_velocity:
    data:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

