--- name:default
device: /dev/input/js0
axisScale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

--- name:thrustmaster
axisScale: [1.0, 1.0, 1.0, -1.0, 1.0, 1.0]

--- name:logitech_attack3
axisScale: [1.0, 1.0, -1.0]

--- name:predator_trust
axisScale: [1.0, 1.0, 0.0, -1.0, 1.0, -1.0, -1.0]

--- name:logitech_gamepad
axisScale: [1.0, 1.0, -1.0, -1.0, 1.0, 1.0]
