--- name:default

--- name:hdpr_slip&obstacles

wheel_radius: 0.125

update_criterias: [SLIP_RATIO, OBSTACLES_DENSITY]

num_terrains: 3 # without considering obstacles

--- name:hdpr_slip

wheel_radius: 0.125

update_criterias: [SLIP_RATIO]

num_terrains: 3 # without considering obstacles
