--- name:default

--- name:hdpr

wheel_radius: 0.125

--- name:slip&obstacles

update_criterias: [SLIP_RATIO, OBSTACLES_DENSITY]

--- name:slip

update_criterias: [SLIP_RATIO]

--- name:decos_3terrains

num_terrains: 3 # without considering obstacles
