#!/usr/bin/env ruby

--- name:default
# The device port
port: /dev/hdpr-gyro
# The device baudrate
baudrate: 921600
# Nominal samping frequency of the sensor in Hz
sampling_frequency: 100
# Start sensor calibration. Read during runtime so the calibration can be started at any time. By default set to false.
calibrate: false
# Number of samples to average over for bias calibration.
calibration_samples: 30
# Bias of the gyroscope z-axis.
bias: -5.6821389404368461e-05
latitude: 52

# Calibrated bias value
--- name:calibration
calibrate: true
calibration_samples: 120000 # 120000 at 100Hz = 20 minutes
