--- name:exoter
# no documentation available for this property
max_pitch: 35.0
# no documentation available for this property
max_roll: 20.0
# no documentation available for this property
max_slip: 0.8
# for hazard avoidance, the detection of an obstacle is not an exception
write_hazard_exception: false
