--- name:exoter
# no documentation available for this property
max_pitch: 35.0
# no documentation available for this property
max_roll: 20.0
# no documentation available for this property
max_slip: 0.8
