--- name:ExoTer
# the device port
serial_port: /dev/ttyXR0
# Baud rate to open the serial com_port.
serial_baudrate: 38400
# the expected time (in seconds) to have a whole package in the fd (the device port)
serial_timeout: 0.2

--- name:HDPR
# the device port
serial_port: /dev/hdpr-dgps
# Baud rate to open the serial com_port.
serial_baudrate: 115200
#serial_baudrate: 9600
# the expected time (in seconds) to have a whole package in the fd (the device port)
serial_timeout: 0.2

--- name:EvaluationBoard
# the device port
serial_port: /dev/ttyUSB1
# Baud rate to open the serial com_port.
serial_baudrate: 38400
# the expected time (in seconds) to have a whole package in the fd (the device port)
serial_timeout: 0.1


--- name:Netherlands
# UTM zone for conversion of WGS84 to UTM
utm_zone: 31
# UTM north for conversion of WGS84 to UTM
utm_north: true
# Geodetic datum typically NAD83 or WGS84 
geodetic_datum: WGS84

# from frame for the transformer
gnss_source_frame: "body" #transformer names. No transformation convention
# to frame for the transformer
gnss_target_frame: "world_osg" #transformer names. No transformation convention

--- name:Spain
# UTM zone for conversion of WGS84 to UTM
utm_zone: 28
# UTM north for conversion of WGS84 to UTM
utm_north: true
# Geodetic datum typically NAD83 or WGS84 
geodetic_datum: WGS84

# from frame for the transformer
gnss_source_frame: "body" #transformer names. No transformation convention
# to frame for the transformer
gnss_target_frame: "world_osg" #transformer names. No transformation convention

--- name:ESTEC
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 597220.14273647161
  - 5786238.5623347349
  - 2.9529999999999998

--- name:DECOS
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 597481.68
  - 5785983.94
  - 5.87
  
--- name:DECOS_AUTONOMY
# Origin in UTM coordinates where the whole DECOS area is well into positive coordinates.
pose_origin:
  data:
  - 597469.22 
  - 5785971.45 
  - 5.87

--- name:TENERIFE_AUTONOMY
# Origin in UTM coordinates where the whole DECOS area is well into positive coordinates.
pose_origin:
  data:
  - 597642.22
  - 5786059.45
  - 2296.00

--- name:Tenerife
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 344043.0
  - 3127403.0
  - 2296.0

--- name:Tenerife_Teleop
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 344182.92
  - 3127638.37
  - 2299.0

--- name:calibration
# Offset to 0 so the value in rock-display would show the value needed to set here
pose_origin:
  data:
  - 0.0
  - 0.0
  - 0.0

# no documentation available for this property
#metadata:
#  metadata: []
#  properties: []
#  input_ports: []
#  output_ports: []

