--- name:default
# Complementary filter weight
alpha: 0.15
# Minimum distance to travel for the first headning estimation (calibration), should be higher than dist_min
calibration_dist_min: 1.0
# Minimum distance to travel for GPS-based heading estimation
dist_min: 1.0
# GPS position offset (x, y, z) with regards to the platform it is mounted on
offset:
  data:
    - 0.6
    - 0
    - -0.3
