--- name:default
# Complementary filter weight
alpha: 0.15
# Minimum distance to travel for the first headning estimation (calibration), should be higher than dist_min
calibration_dist_min: 1.0
# Minimum distance to travel for GPS-based heading estimation
dist_min: 0.2
