--- name:default
config:
    calibrationPath: "/home/marta/rock/hazardCalibration.txt"
    tolerance_close: 0.3 # [m]
    tolerance_far: 0.7 # [m]
    hazardPixelLimit: 50
    newCalibration: false
    numCalibrationSamples: 100
    mask: # -1 means full extension to the respective side
        minX: 180
        maxX: 990
        minY: 375
        maxY: 555
    dist_to_left_edge: -0.77
    dist_to_right_edge: 0.93
    dist_to_bottom_edge: 1.14
    dist_to_upper_edge: 1.73
    trav_map:
        width: 4.0
        height: 4.0
        resolution: 0.1

--- name:bb3
config:
    calibrationPath: "/home/levin/rock/hazardCalibrationBB3.txt"
    tolerance_close: 0.2 # [m]
    tolerance_far: 1.0 # [m]
    hazardPixelLimit: 20
    newCalibration: false
    numCalibrationSamples: 20
    mask: # -1 means full extension to the respective side
        minX: -1
        maxX: -1
        minY: 450
        maxY: -1

--- name:bb2
config:
    calibrationPath: "/home/marta/rock/hazardCalibrationBB2.txt"
    tolerance_close: 0.2 # [m]
    tolerance_far: 1.0 # [m]
    hazardPixelLimit: 20
    newCalibration: false
    numCalibrationSamples: 20
    mask: # -1 means full extension to the respective side
        minX: -1
        maxX: -1
        minY: 650
        maxY: 750

--- name:pancam
config:
    calibrationPath: "/home/levin/rock/hazardCalibrationPanCam.txt"
    tolerance_close: 0.2 # [m]
    tolerance_far: 1.0 # [m]
    hazardPixelLimit: 20
    newCalibration: false
    numCalibrationSamples: 20
    mask: # -1 means full extension to the respective side
        minX: -1
        maxX: -1
        minY: 450
        maxY: -1
