--- name:default
config:
    calibration_path: "/home/marta/rock/hazardCalibration.txt"
    tolerance_close: 0.3 # [m]
    tolerance_far: 0.7 # [m]
    hazard_pixel_limit: 300
    new_calibration: false
    num_calibration_samples: 100
    mask: # -1 means full extension to the respective side
        min_x: 220
        max_x: 990
        min_y: 375
        max_y: 555
    dist_to_left_edge: -0.74
    dist_to_right_edge: 0.94
    dist_to_bottom_edge: 1.04
    dist_to_upper_edge: 1.63
    trav_map:
        width: 4.0
        height: 4.0
        resolution: 0.1
