--- name:default
config:
    calibrationPath: "/home/marta/rock/hazardCalibration.txt"
    tolerance: 0.4 # [m]
    hazardPixelLimit: 20
    newCalibration: false
    numCalibrationSamples: 20
    mask: # -1 means full extension to the respective side
        minX: -1
        maxX: -1
        minY: 650
        maxY: 750

--- name:bb3
config:
    calibrationPath: "/home/levin/rock/hazardCalibrationBB3.txt"
    tolerance: 0.2 # [m]
    hazardPixelLimit: 20
    newCalibration: false
    numCalibrationSamples: 20
    mask: # -1 means full extension to the respective side
        minX: -1
        maxX: -1
        minY: 450
        maxY: -1

--- name:bb2
config:
    calibrationPath: "/home/marta/rock/hazardCalibrationBB2.txt"
    tolerance: 0.2 # [m]
    hazardPixelLimit: 20
    newCalibration: false
    numCalibrationSamples: 20
    mask: # -1 means full extension to the respective side
        minX: -1
        maxX: -1
        minY: 650
        maxY: 750

--- name:pancam
config:
    calibrationPath: "/home/levin/rock/hazardCalibrationPanCam.txt"
    tolerance: 0.2 # [m]
    hazardPixelLimit: 20
    newCalibration: false
    numCalibrationSamples: 20
    mask: # -1 means full extension to the respective side
        minX: -1
        maxX: -1
        minY: 450
        maxY: -1
