--- name:default
config:
    calibrationPath: "/home/levin/rock/hazardCalibration.txt"
    tolerance: 0.2 # [m]
    hazardPixelLimit: 20
    newCalibration: true
    numCalibrationSamples: 20
    mask: # -1 means full extension to the respective side
        minX: -1
        maxX: -1
        minY: 450
        maxY: -1
