--- name:default
point_cloud_height: 144
point_cloud_width: 176

# from frame for the transformer frame names
icp_odometry_source_frame: "body"
# to frame for the transformer frame names
icp_odometry_target_frame: "navigation"

# Configuration parameters for the ICP.
gicp_config:
  maximum_iterations: 200 #the maximum number of iterations the internal optimization should run for
  maximum_optimizer_iterations: 100 # maximum number of iterations at the optimization step
  ransac_iterations: 40 # is the number of iterations RANSAC should run for
  ransac_oulier_threshold: 0.05 # the inlier distance threshold for the internal RANSAC outlier rejection loop. The value is set by default to 0.05m.
  transformation_epsilon: 0.0005 #the transformation epsilon in order for an optimization to be considered as having converged to the final solution.
  rotation_epsilon: 0.002 # the rotation epsilon in order for an optimization to be considered as having converged to the final solution.
  euclidean_fitness_epsilon: 1.0 #the maximum allowed distance error before the algorithm will be considered to have converged. error between two consecutive steps in the ICP loop
  max_correspondence_distance: 5 #distance threshold between two correspondent points in source <-> targe. If the distance is larger than this threshold, the points will be ignored in the alignment process
  correspondence_randomness: 20 # the number of neighbors to use when computing covariances
  max_fitness_score: 1.0 #maximum allowed fitness score


# Set to true if output debug information is desirable.
output_debug: true

# Time in s between point_cloud_source readings
point_cloud_source_period: 0.5
# Time in s between point_cloud_target readings
point_cloud_target_period: 0.5

# list of static transformations
static_transformations: []

# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.2
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 0.5

outlierfilter_config:
  type: NONE

--- name:bilateral
# Configuration parameters for the bilateral filter.
bfilter_config:
  filterOn: true
  spatial_width: 2.0 #size of the window bilateral filter
  range_sigma: 0.02 #the standard deviation of the Gaussian for the intensity difference

--- name:pass
# Configuration parameters for Pass filter.
passfilter_config:
    filterOn: true
    axis_name: 'x'
    limit:
        data:
        - 0.0
        - 0.4

--- name:statistical
# Configuration parameters for Radius Outlier Removal filter.
outlierfilter_config:
  type: STATISTICAL
  parameter_one: 30 #the number of nearest neighbors to use for mean distance estimation (nr_k)
  parameter_two: 1.0 #the standard deviation multiplier for the distance threshold calculation.(stddev_null)

--- name:radius
# Configuration parameters for Radius Outlier Removal filter.
outlierfilter_config:
  type: RADIUS
  parameter_one: 0.2 #Get the radius of the sphere that will determine which points are neighbors.
  parameter_two: 70 #number of neighbors that need to be present in order to be classified as an inlier

