--- name:default
# path to the rover urdf file
urdf_file: '../../../../bundles/exoter/data/odometry/exoter_odometry_model_complete.urdf'

# Output frequency of the proprioceptive sensors (joints, inertial sensors and orientation).
proprioceptive_output_frequency: 12.5

# from frame for the transformer
orientation_source_frame: "body"
# to frame for the transformer
orientation_target_frame: "navigation"

# Effective wheel radius average for odometry
wheel_radius_joint_names: [fl_wheel]

passive_offset_joint_name: "left_bogie"

# Locomotion joints searching by names.
#joint_names: [left_passive, right_passive, rear_passive, fl_walking, fr_walking, ml_walking, mr_walking, rl_walking, rr_walking, fl_steer, fr_steer, rl_steer, rr_steer, fl_drive, fr_drive, ml_drive, mr_drive, rl_drive, rr_drive]
all_joint_names: [left_passive, fl_mimic, fl_walking, fl_steer, fl_drive, fl_contact, fl_translation, fl_slipx, fl_slipy, fl_slipz,
                            ml_mimic, ml_walking, ml_drive, ml_contact, ml_translation, ml_slipx, ml_slipy, ml_slipz,
                      rear_passive, rl_mimic, rl_walking, rl_steer, rl_drive, rl_contact, rl_translation, rl_slipx, rl_slipy, rl_slipz,
                            rr_mimic, rr_walking, rr_steer, rr_drive, rr_contact, rr_translation, rr_slipx, rr_slipy, rr_slipz,
                      right_passive, fr_mimic, fr_walking, fr_steer, fr_drive, fr_contact, fr_translation, fr_slipx, fr_slipy, fr_slipz,
                            mr_mimic, mr_walking, mr_drive, mr_contact, mr_translation, mr_slipx, mr_slipy, mr_slipz]

contact_point_segments: [fl_segment_slipz, fr_segment_slipz, ml_segment_slipz, mr_segment_slipz, rl_segment_slipz, rr_segment_slipz]

contact_angle_segments: [fl_ground, fr_ground, ml_ground, mr_ground, rl_ground, rr_ground]

slip_joint_names: [fl_slipx, fr_slipx, ml_slipx, mr_slipx, rl_slipx, rr_slipx,
              fl_slipy, fr_slipy, ml_slipy, mr_slipy, rl_slipy, rr_slipy,
              fl_slipz, fr_slipz, ml_slipz, mr_slipz, rl_slipz, rr_slipz]

contact_joint_names: [fl_contact, fr_contact, ml_contact, mr_contact, rl_contact, rr_contact]

zero_position_joint_names: [fl_drive, fr_drive, ml_drive, mr_drive, rl_drive, rr_drive, fl_translation, fr_translation, ml_translation, mr_translation, rl_translation, rr_translation]

zero_speed_joint_names: [fl_drive, fr_drive, ml_drive, mr_drive, rl_drive, rr_drive]

mimic_joint_names:
  names: [fl_mimic, fr_mimic, ml_mimic, mr_mimic, rl_mimic, rr_mimic]
  elements: [left_passive, right_passive, left_passive, right_passive, rear_passive, rear_passive]

translation_joint_names:
  names: [fl_translation, fr_translation, ml_translation, mr_translation, rl_translation, rr_translation]
  elements: [fl_drive, fr_drive, ml_drive, mr_drive, rl_drive, rr_drive]

# Joints in which the IIR wants to be apply. These joints names MUST be also contained in the joint_names. Maximum number of three joints. In case more joints are required you need to change the code due to template classes. IIR_FILTER_VECTOR_SIZE
filter_joint_names: [left_passive, right_passive, rear_passive]

# Time in s between joints_samples readings
joints_samples_period: 0.08
# Time in s between inertial_samples readings
inertial_samples_period: 0.008
# Time in s between orientation_samples readings
orientation_samples_period: 0.008
# Minimum system time in seconds between two updates of the status ports
stream_aligner_status_period: 1.0
# Maximum time in seconds the transformer will wait until it starts dropping samples
aggregator_max_latency: 1.0

#T_body_to_imu which transform samples from imu-frame to body-frame.
body_to_imu_transformation:
  time:
    microseconds: 0
  sourceFrame: 'imu'
  targetFrame: 'body'
  position:
    data:
    - 0.00417
    - -0.0399
    - 0.0052
  cov_position:
    data:
    - .nan
    - .nan
    - .nan
    - .nan
    - .nan
    - .nan
    - .nan
    - .nan
    - .nan
  orientation:
    im:
    - 0.0
    - 0.0
    - 1.0
    re: 0.0

--- name:hamming1hzsampling12hz
#Configuration values for the Finite Impulse Response (FIR). Wp = 1.0hz/6.25 (nyquist_rate).
filter_config:
  filterOn: true  #True or false
  feedForwardCoeff:
    data:
    - 2.55462975e-10
    - -1.25434931e-03
    - -3.48982195e-03
    - -6.81653325e-03
    - -9.90524645e-03
    - -9.88463443e-03
    - -3.12431128e-03
    - 1.32868891e-02
    - 3.99432385e-02
    - 7.41325533e-02
    - 1.10005131e-01
    - 1.40001589e-01
    - 1.57105495e-01
    - 1.57105495e-01
    - 1.40001589e-01
    - 1.10005131e-01
    - 7.41325533e-02
    - 3.99432385e-02
    - 1.32868891e-02
    - -3.12431128e-03
    - -9.88463443e-03
    - -9.90524645e-03
    - -6.81653325e-03
    - -3.48982195e-03
    - -1.25434931e-03
    - 2.55462975e-10

