--- name:default

scriptFile: 'Coupled_motion_planner'
pathVariable: 'finalRoverPath'
headingVariable: 'finalRoverHeading'
jointsVariable: 'finalJoints'
assignmentVariable: 'assignment'
numJoints: 5


xm: 7
ym: 6
xr: 1.5
yr: 1
initHeading: 0 
mapDirectory: '/home/ares/rock/bundles/rover/data/maps/prl/'
resolution: 0.02
size: 8.91

