
--- name:default
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 60.0, 90] #38.57] #52.857] #38.5714] #81.42857] #260]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.02, 0.07, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 0
# Pan position (double) in radians to be executed
commandsPan: 0
# Tilt position (double) in radians to be executed
commandsTilt: 0.628 #60deg=1.046666667 #50deg=0.872222222 #40deg=0.697777778 #37.3deg=0.650677778 #36deg=0.628


--- name:point_turn
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 25.0] #38.5714] #81.42857] #260]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.0, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, -0.05, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed
commandsPan: 0
# Tilt position (double) in radians to be executed
commandsTilt: 0.628 #60deg=1.046666667 #50deg=0.872222222 #40deg=0.697777778 #37.3deg=0.650677778 #36deg=0.628


--- name:L_trajectory
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 50.0, 65.0, 80.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.07, 0.0, 0.07, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, -0.05, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1, 1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed
commandsPan: 0
# Tilt position (double) in radians to be executed
commandsTilt: 0.650677778 #60deg=1.046666667 #50deg=0.872222222 #40deg=0.697777778 #37.3deg=0.650677778 #36deg=0.628


--- name:stationary
# List containing time to execute the commands
commandsTime:           [0.0, 130]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [ 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed
commandsPan: 0
# Tilt position (double) in radians to be executed
commandsTilt: 0.35 #0.523598776 0,348888889 0,872222222 0,872222222


--- name:ptu_test
# List containing time to execute the commands
commandsTime:           [0.0, 5.0, 10.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.0, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed (zero seems to be pan=0.102386)
commandsPan: 0
# Tilt position (double) in radians to be executed (zero seems to be tilt=0.159381)
commandsTilt: 0.523598776


--- name:imu_test
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 30.0, 40.0, 50.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.07, 0.03, 0.04, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, -0.03, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1, 1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed
commandsPan: 1
# Tilt position (double) in radians to be executed
commandsTilt: 1


--- name:wheel_walking
# List containing time to execute the commands
commandsTime:           [0.0, 2.0, 32.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.07, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [2, 2, 2]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed
commandsPan: 1
# Tilt position (double) in radians to be executed
commandsTilt: 1


--- name:backwards_5m
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 110.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.05, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed
commandsPan: 1
# Tilt position (double) in radians to be executed
commandsTilt: 1


--- name:backwards_4m
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 76.666667]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, -0.06, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed
commandsPan: 1
# Tilt position (double) in radians to be executed
commandsTilt: 1


--- name:forward_1m
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 30.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.05, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed
commandsPan: 1
# Tilt position (double) in radians to be executed
commandsTilt: 1


--- name:backward_1m
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 30.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, -0.05, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]
# Flag to execute or not a PTU position command at the beginning
commandsPTU: 1
# Pan position (double) in radians to be executed
commandsPan: 1
# Tilt position (double) in radians to be executed
commandsTilt: 1



