
--- name:default
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 81.42857]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.07, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]


--- name:imu_test
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 30.0, 40.0, 50.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.07, 0.03, 0.04, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, -0.03, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1, 1, 1]


--- name:wheel_walking
# List containing time to execute the commands
commandsTime:           [0.0, 2.0, 32.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.07, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [2, 2, 2]


--- name:backwards_5m
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 110.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.05, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]


--- name:backwards_4m
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 76.666667]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, -0.06, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]


--- name:forward_1m
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 30.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, 0.05, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]

--- name:backward_1m
# List containing time to execute the commands
commandsTime:           [0.0, 10.0, 30.0]
# List containing the translation velocity command associated to the CommandsTimes
commandsTranslation:    [0.0, -0.05, 0.0]
# List containing the rotation velocity command associated to the CommandsTimes
commandsRotation:       [0.0, 0.0, 0.0]
# List containing the locomotion_mode switches associated to the CommandsTimes
# 1 = DRIVING
# 2 = WHEEL_WALKING
commandsLocomotionMode: [1, 1, 1]
