--- name:default
# Minimum delay in milliseconds before saving a frame after the PanCam reaches its goal position
frameDelayTimeMs: 100
# PanCam pan and tilt position error margin
positionErrorMargin: 0.1

# Camera pan/tilt orientations for pictures
--- name:separation_40
cameraPositions:
  - data:
    - -155.0
    - 20.0
  - data:
    - -120.0
    - 20.0
  - data:
    - -80.0
    - 20.0
  - data:
    - -40.0
    - 20.0
  - data:
    - 0.0
    - 20.0
  - data:
    - 40.0
    - 20.0
  - data:
    - 80.0
    - 20.0
  - data:
    - 120.0
    - 20.0
  - data:
    - 155.0
    - 20.0

--- name:separation_40_30
cameraPositions:
# First pass, 30 degrees above the horizont, 40 degrees steps
  - data:
    - -175.0
    - -30.0
  - data:
    - -160.0
    - -30.0
  - data:
    - -120.0
    - -30.0
  - data:
    - -80.0
    - -30.0
  - data:
    - -40.0
    - -30.0
  - data:
    - 0.0
    - -30.0
  - data:
    - 40.0
    - -30.0
  - data:
    - 80.0
    - -30.0
  - data:
    - 120.0
    - -30.0
  - data:
    - 160.0
    - -30.0
  - data:
    - 175.0
    - -30.0
# Second pass
  - data:
    - 175.0
    - 0.0
  - data:
    - 160.0
    - 0.0
  - data:
    - 120.0
    - 0.0
  - data:
    - 80.0
    - 0.0
  - data:
    - 40.0
    - 0.0
  - data:
    - 0.0
    - 0.0
  - data:
    - -40.0
    - 0.0
  - data:
    - -80.0
    - 0.0
  - data:
    - -120.0
    - 0.0
  - data:
    - -160.0
    - 0.0
  - data:
    - -175.0
    - 0.0
# Third pass
  - data:
    - -175.0
    - 30.0
  - data:
    - -160.0
    - 30.0
  - data:
    - -120.0
    - 30.0
  - data:
    - -80.0
    - 30.0
  - data:
    - -40.0
    - 30.0
  - data:
    - 0.0
    - 30.0
  - data:
    - 40.0
    - 30.0
  - data:
    - 80.0
    - 30.0
  - data:
    - 120.0
    - 30.0
  - data:
    - 160.0
    - 30.0
  - data:
    - 175.0
    - 30.0
# Fourth pass
  - data:
    - 175.0
    - 60.0
  - data:
    - 160.0
    - 60.0
  - data:
    - 120.0
    - 60.0
  - data:
    - 80.0
    - 60.0
  - data:
    - 40.0
    - 60.0
  - data:
    - 0.0
    - 60.0
  - data:
    - -40.0
    - 60.0
  - data:
    - -80.0
    - 60.0
  - data:
    - -120.0
    - 60.0
  - data:
    - -160.0
    - 60.0
  - data:
    - -175.0
    - 60.0
# Directly point down
  - data:
    - -175.0
    - 80.0

--- name:separation_30
cameraPositions:
  - data:
    - -155.0
    - 20.0
  - data:
    - -150.0
    - 20.0
  - data:
    - -120.0
    - 20.0
  - data:
    - -90.0
    - 20.0
  - data:
    - -60.0
    - 20.0
  - data:
    - -30.0
    - 20.0
  - data:
    - 0.0
    - 20.0
  - data:
    - 30.0
    - 20.0
  - data:
    - 60.0
    - 20.0
  - data:
    - 90.0
    - 20.0
  - data:
    - 120.0
    - 20.0
  - data:
    - 150.0
    - 20.0
  - data:
    - 155.0
    - 20.0

--- name:separation_20
cameraPositions:
  - data:
    - -155.0
    - 20.0
  - data:
    - -140.0
    - 20.0
  - data:
    - -120.0
    - 20.0
  - data:
    - -100.0
    - 20.0
  - data:
    - -80.0
    - 20.0
  - data:
    - -60.0
    - 20.0
  - data:
    - -40.0
    - 20.0
  - data:
    - -20.0
    - 20.0
  - data:
    - 0.0
    - 20.0
  - data:
    - 20.0
    - 20.0
  - data:
    - 40.0
    - 20.0
  - data:
    - 60.0
    - 20.0
  - data:
    - 80.0
    - 20.0
  - data:
    - 100.0
    - 20.0
  - data:
    - 120.0
    - 20.0
  - data:
    - 140.0
    - 20.0
  - data:
    - 155.0
    - 20.0

--- name:apriltag
cameraPositions:
  - data:
    - -180.0
    - 60.0
