--- name:default
# Minimum delay in milliseconds before saving a frame after the PanCam reaches its goal position
frameDelayTimeMs: 100
# PanCam pan position center
positionCenter: 0.0
# PanCam pan position error margin
positionErrorMargin: 0.1
# PanCam pan position left
positionLeft: -30
# PanCam pan position right
positionRight: 30
# PanCam tilt position for all positions
positionTilt: 30
# Axis resolution per position moved (in seconds/arc)
resolutionPerPosition: 185.1429
