--- name:default
# Minimum delay in milliseconds before saving a frame after the PanCam reaches its goal position
frameDelayTimeMs: 100
# PanCam pan and tilt position error margin
positionErrorMargin: 0.1

# Camera pan/tilt orientations for pictures
--- name:separation_40
cameraPositions:
  - data:
    - -159.0
    - 20.0
  - data:
    - -120.0
    - 20.0
  - data:
    - -80.0
    - 20.0
  - data:
    - -40.0
    - 20.0
  - data:
    - 0.0
    - 20.0
  - data:
    - 40.0
    - 20.0
  - data:
    - 80.0
    - 20.0
  - data:
    - 120.0
    - 20.0
  - data:
    - 159.0
    - 20.0

--- name:separation_40_30
cameraPositions:
# First pass
  - data:
    - -159.0
    - -30.0
  - data:
    - -120.0
    - -30.0
  - data:
    - -80.0
    - -30.0
  - data:
    - -40.0
    - -30.0
  - data:
    - 0.0
    - -30.0
  - data:
    - 40.0
    - -30.0
  - data:
    - 80.0
    - -30.0
  - data:
    - 120.0
    - -30.0
  - data:
    - 159.0
    - -30.0
# Second pass
  - data:
    - 159.0
    - 0.0
  - data:
    - 120.0
    - 0.0
  - data:
    - 80.0
    - 0.0
  - data:
    - 40.0
    - 0.0
  - data:
    - 0.0
    - 0.0
  - data:
    - -40.0
    - 0.0
  - data:
    - -80.0
    - 0.0
  - data:
    - -120.0
    - 0.0
  - data:
    - -159.0
    - 0.0
# Third pass
  - data:
    - -159.0
    - 30.0
  - data:
    - -120.0
    - 30.0
  - data:
    - -80.0
    - 30.0
  - data:
    - -40.0
    - 30.0
  - data:
    - 0.0
    - 30.0
  - data:
    - 40.0
    - 30.0
  - data:
    - 80.0
    - 30.0
  - data:
    - 120.0
    - 30.0
  - data:
    - 159.0
    - 30.0
# Fourth pass
#  - data:
#    - 159.0
#    - 45.0
#  - data:
#    - 120.0
#    - 45.0
#  - data:
#    - 80.0
#    - 45.0
#  - data:
#    - 40.0
#    - 45.0
#  - data:
#    - 0.0
#    - 45.0
#  - data:
#    - -40.0
#    - 45.0
#  - data:
#    - -80.0
#    - 45.0
#  - data:
#    - -120.0
#    - 45.0
#  - data:
#    - -159.0
#    - 45.0

--- name:separation_30
cameraPositions:
  - data:
    - -159.0
    - 20.0
  - data:
    - -150.0
    - 20.0
  - data:
    - -120.0
    - 20.0
  - data:
    - -90.0
    - 20.0
  - data:
    - -60.0
    - 20.0
  - data:
    - -30.0
    - 20.0
  - data:
    - 0.0
    - 20.0
  - data:
    - 30.0
    - 20.0
  - data:
    - 60.0
    - 20.0
  - data:
    - 90.0
    - 20.0
  - data:
    - 120.0
    - 20.0
  - data:
    - 150.0
    - 20.0
  - data:
    - 159.0
    - 20.0

--- name:separation_20
cameraPositions:
  - data:
    - -159.0
    - 20.0
  - data:
    - -140.0
    - 20.0
  - data:
    - -120.0
    - 20.0
  - data:
    - -100.0
    - 20.0
  - data:
    - -80.0
    - 20.0
  - data:
    - -60.0
    - 20.0
  - data:
    - -40.0
    - 20.0
  - data:
    - -20.0
    - 20.0
  - data:
    - 0.0
    - 20.0
  - data:
    - 20.0
    - 20.0
  - data:
    - 40.0
    - 20.0
  - data:
    - 60.0
    - 20.0
  - data:
    - 80.0
    - 20.0
  - data:
    - 100.0
    - 20.0
  - data:
    - 120.0
    - 20.0
  - data:
    - 140.0
    - 20.0
  - data:
    - 159.0
    - 20.0

--- name:separation_10
cameraPositions:
  - data:
    - -159.0
    - 20.0
  - data:
    - -150.0
    - 20.0
  - data:
    - -140.0
    - 20.0
  - data:
    - -130.0
    - 20.0
  - data:
    - -120.0
    - 20.0
  - data:
    - -110.0
    - 20.0
  - data:
    - -100.0
    - 20.0
  - data:
    - -90.0
    - 20.0
  - data:
    - -80.0
    - 20.0
  - data:
    - -70.0
    - 20.0
  - data:
    - -60.0
    - 20.0
  - data:
    - -50.0
    - 20.0
  - data:
    - -40.0
    - 20.0
  - data:
    - -30.0
    - 20.0
  - data:
    - -20.0
    - 20.0
  - data:
    - -10.0
    - 20.0
  - data:
    - 0.0
    - 20.0
  - data:
    - 10.0
    - 20.0
  - data:
    - 20.0
    - 20.0
  - data:
    - 30.0
    - 20.0
  - data:
    - 40.0
    - 20.0
  - data:
    - 50.0
    - 20.0
  - data:
    - 60.0
    - 20.0
  - data:
    - 70.0
    - 20.0
  - data:
    - 80.0
    - 20.0
  - data:
    - 90.0
    - 20.0
  - data:
    - 100.0
    - 20.0
  - data:
    - 110.0
    - 20.0
  - data:
    - 120.0
    - 20.0
  - data:
    - 130.0
    - 20.0
  - data:
    - 140.0
    - 20.0
  - data:
    - 150.0
    - 20.0
  - data:
    - 159.0
    - 20.0

--- name:separation_10_10
cameraPositions:
# First pass, look the sky
  - data:
    - -159.0
    - -30.0
  - data:
    - -150.0
    - -30.0
  - data:
    - -140.0
    - -30.0
  - data:
    - -130.0
    - -30.0
  - data:
    - -120.0
    - -30.0
  - data:
    - -110.0
    - -30.0
  - data:
    - -100.0
    - -30.0
  - data:
    - -90.0
    - -30.0
  - data:
    - -80.0
    - -30.0
  - data:
    - -70.0
    - -30.0
  - data:
    - -60.0
    - -30.0
  - data:
    - -50.0
    - -30.0
  - data:
    - -40.0
    - -30.0
  - data:
    - -30.0
    - -30.0
  - data:
    - -20.0
    - -30.0
  - data:
    - -10.0
    - -30.0
  - data:
    - 0.0
    - -30.0
  - data:
    - 10.0
    - -30.0
  - data:
    - 20.0
    - -30.0
  - data:
    - 30.0
    - -30.0
  - data:
    - 40.0
    - -30.0
  - data:
    - 50.0
    - -30.0
  - data:
    - 60.0
    - -30.0
  - data:
    - 70.0
    - -30.0
  - data:
    - 80.0
    - -30.0
  - data:
    - 90.0
    - -30.0
  - data:
    - 100.0
    - -30.0
  - data:
    - 110.0
    - -30.0
  - data:
    - 120.0
    - -30.0
  - data:
    - 130.0
    - -30.0
  - data:
    - 140.0
    - -30.0
  - data:
    - 150.0
    - -30.0
  - data:
    - 159.0
    - -30.0
# Look above the horizont
  - data:
    - 159.0
    - -10.0
  - data:
    - 150.0
    - -10.0
  - data:
    - 140.0
    - -10.0
  - data:
    - 130.0
    - -10.0
  - data:
    - 120.0
    - -10.0
  - data:
    - 110.0
    - -10.0
  - data:
    - 100.0
    - -10.0
  - data:
    - 90.0
    - -10.0
  - data:
    - 80.0
    - -10.0
  - data:
    - 70.0
    - -10.0
  - data:
    - 60.0
    - -10.0
  - data:
    - 50.0
    - -10.0
  - data:
    - 40.0
    - -10.0
  - data:
    - 30.0
    - -10.0
  - data:
    - 20.0
    - -10.0
  - data:
    - 10.0
    - -10.0
  - data:
    - 0.0
    - -10.0
  - data:
    - -10.0
    - -10.0
  - data:
    - -20.0
    - -10.0
  - data:
    - -30.0
    - -10.0
  - data:
    - -40.0
    - -10.0
  - data:
    - -50.0
    - -10.0
  - data:
    - -60.0
    - -10.0
  - data:
    - -70.0
    - -10.0
  - data:
    - -80.0
    - -10.0
  - data:
    - -90.0
    - -10.0
  - data:
    - -100.0
    - -10.0
  - data:
    - -110.0
    - -10.0
  - data:
    - -120.0
    - -10.0
  - data:
    - -130.0
    - -10.0
  - data:
    - -140.0
    - -10.0
  - data:
    - -150.0
    - -10.0
  - data:
    - -159.0
    - -10.0
# Look below the horizont
  - data:
    - -159.0
    - 10.0
  - data:
    - -150.0
    - 10.0
  - data:
    - -140.0
    - 10.0
  - data:
    - -130.0
    - 10.0
  - data:
    - -120.0
    - 10.0
  - data:
    - -110.0
    - 10.0
  - data:
    - -100.0
    - 10.0
  - data:
    - -90.0
    - 10.0
  - data:
    - -80.0
    - 10.0
  - data:
    - -70.0
    - 10.0
  - data:
    - -60.0
    - 10.0
  - data:
    - -50.0
    - 10.0
  - data:
    - -40.0
    - 10.0
  - data:
    - -30.0
    - 10.0
  - data:
    - -20.0
    - 10.0
  - data:
    - -10.0
    - 10.0
  - data:
    - 0.0
    - 10.0
  - data:
    - 10.0
    - 10.0
  - data:
    - 20.0
    - 10.0
  - data:
    - 30.0
    - 10.0
  - data:
    - 40.0
    - 10.0
  - data:
    - 50.0
    - 10.0
  - data:
    - 60.0
    - 10.0
  - data:
    - 70.0
    - 10.0
  - data:
    - 80.0
    - 10.0
  - data:
    - 90.0
    - 10.0
  - data:
    - 100.0
    - 10.0
  - data:
    - 110.0
    - 10.0
  - data:
    - 120.0
    - 10.0
  - data:
    - 130.0
    - 10.0
  - data:
    - 140.0
    - 10.0
  - data:
    - 150.0
    - 10.0
  - data:
    - 159.0
    - 10.0
# Look down
  - data:
    - 159.0
    - 30.0
  - data:
    - 150.0
    - 30.0
  - data:
    - 140.0
    - 30.0
  - data:
    - 130.0
    - 30.0
  - data:
    - 120.0
    - 30.0
  - data:
    - 110.0
    - 30.0
  - data:
    - 100.0
    - 30.0
  - data:
    - 90.0
    - 30.0
  - data:
    - 80.0
    - 30.0
  - data:
    - 70.0
    - 30.0
  - data:
    - 60.0
    - 30.0
  - data:
    - 50.0
    - 30.0
  - data:
    - 40.0
    - 30.0
  - data:
    - 30.0
    - 30.0
  - data:
    - 20.0
    - 30.0
  - data:
    - 10.0
    - 30.0
  - data:
    - 0.0
    - 30.0
  - data:
    - -10.0
    - 30.0
  - data:
    - -20.0
    - 30.0
  - data:
    - -30.0
    - 30.0
  - data:
    - -40.0
    - 30.0
  - data:
    - -50.0
    - 30.0
  - data:
    - -60.0
    - 30.0
  - data:
    - -70.0
    - 30.0
  - data:
    - -80.0
    - 30.0
  - data:
    - -90.0
    - 30.0
  - data:
    - -100.0
    - 30.0
  - data:
    - -110.0
    - 30.0
  - data:
    - -120.0
    - 30.0
  - data:
    - -130.0
    - 30.0
  - data:
    - -140.0
    - 30.0
  - data:
    - -150.0
    - 30.0
  - data:
    - -159.0
    - 30.0

