--- name:default
# Minimum delay in milliseconds before saving a frame after the PanCam reaches its goal position
frameDelayTimeMs: 100
# PanCam pan and tilt position error margin
positionErrorMargin: 0.1

--- name:separation_40_x
cameraPositions:
# Single pass, 40 degrees steps in Pan, tilt taken from input port value.
  - data:
    - -160.0
    - 0.0
  - data:
    - -120.0
    - 0.0
  - data:
    - -80.0
    - 0.0
  - data:
    - -40.0
    - 0.0
  - data:
    - 0.0
    - 0.0
  - data:
    - 40.0
    - 0.0
  - data:
    - 80.0
    - 0.0
  - data:
    - 120.0
    - 0.0
  - data:
    - 160.0
    - 0.0

