--- name:default
# no documentation available for this property
config:
  shutterCompPeriod: 3
  initShutterTime: 3
  maxShutterTime: 3904
  minShutterTime: 3
  maxIntensity: 255
  factMaxIntensity: 0.65
  factMinIntensity: 0.20
  factNumTooBright: 0.20
  factNumTooDark: 0.10
  factMinMean: 0.30
  factMaxMean: 0.40
  precision: 64.0
