--- name:default
# albeit producing relatively dark images,
# this configuration has shown to yield good disparities in daylight settings
config:
  shutterCompPeriod: 3
  initShutterTime: 400
  maxShutterTime: 3904
  minShutterTime: 3
  maxIntensity: 255
  factMaxIntensity: 0.70
  factMinIntensity: 0.20
  factMinMean: 0.3
  factMaxMean: 0.4
# weightOldShutterTime: 0.995
