--- name:default
# albeit producing relatively dark images,
# this configuration has shown to yield good disparities in daylight settings
config:
  shutterCompPeriod: 3
  initShutterTime: 2000
  maxShutterTime: 3904
  minShutterTime: 3
  maxIntensity: 255
  factMaxIntensity: 0.50
  factMinIntensity: 0.10
  factMinMean: 0.25
  factMaxMean: 0.30
