--- name:exoter

num_motors: 18

num_joints: 21

joint_vrep_names: [joint_drive_fl, joint_drive_fr, joint_drive_ml, joint_drive_mr,
joint_drive_rl, joint_drive_rr, joint_steer_fl, joint_steer_fr, joint_steer_rl,
joint_steer_rr, joint_walk_fl, joint_walk_fr, joint_walk_ml, joint_walk_mr,
joint_walk_rl, joint_walk_rr, bogie_lateral_l, bogie_lateral_r, bogie_rear1, pan, tilt]

joint_readings_names: [WHEEL_DRIVE_FL, WHEEL_DRIVE_FR, WHEEL_DRIVE_CL, WHEEL_DRIVE_CR, WHEEL_DRIVE_BL, WHEEL_DRIVE_BR, WHEEL_STEER_FL, WHEEL_STEER_FR, WHEEL_STEER_BL, WHEEL_STEER_BR, WHEEL_WALK_FL, WHEEL_WALK_FR, WHEEL_WALK_CL, WHEEL_WALK_CR, WHEEL_WALK_BL, WHEEL_WALK_BR, MAST_PAN, MAST_TILT, LEFT_PASSIVE, RIGHT_PASSIVE, BACK_PASSIVE]

ptu_vrep_names: [pan, tilt]

ptu_readings_names: [MAST_PAN, MAST_TILT]


--- name:hdpr

num_motors: 10

num_joints: 14

joint_vrep_names: [joint_drive_fl, joint_drive_fr, joint_drive_ml, joint_drive_mr,
joint_drive_rl, joint_drive_rr, joint_steer_fl, joint_steer_fr, joint_steer_rl,
joint_steer_rr, joint_bogie_left_bottom, joint_bogie_right_bottom, joint_bogie_left_top, joint_bogie_right_top]

joint_readings_names: [WHEEL_DRIVE_FL, WHEEL_DRIVE_FR, WHEEL_DRIVE_CL, WHEEL_DRIVE_CR, WHEEL_DRIVE_BL, WHEEL_DRIVE_BR, WHEEL_STEER_FL, WHEEL_STEER_FR, WHEEL_STEER_BL, WHEEL_STEER_BR, LEFT_ROCKER, RIGHT_ROCKER, LEFT_BOGIE, RIGHT_BOGIE]



