--- name:hdpr
# Size of the kernel used in the laplacian to detect rocks edges
laplacian_kernel_size: 9
# Threshold of the laplacian to detect rocks edges. It is not zet tied to a physical property.
laplacian_threshold: 100.0
# Resolution of each cell in meters
map_resolution: 0.1
# Size of the map height in meters
map_size_height: 10.0
# Size of the map width in meters
map_size_width: 10.0
# First obstacle dilation iterations
obstacle_iterations: 2
# Kernel size to dilate obstacle first time [cells]
obstacle_kernel_size: 3
# Second obstacle dilation iterations (area surrounding an obstacle)
obstacle_vicinity_iterations: 3
# Kernel size to dilate obstacle second time [cells]
obstacle_vicinity_kernel_size: 3
# in meters, needed for obstacle dilation
robot_size: 0.6
# Obstacles the rover can tolerate when there is no sinkage [m]
rover_obstacle_clearance: 0.2
# Slope the rover can travel in nominal case [rad]
rover_slope_gradeability: 0.262 # 15 deg
# How many normal cell a slope map cell will contain
slope_map_scale: 3

--- name:exoter
# Size of the kernel used in the laplacian to detect rocks edges
laplacian_kernel_size: 9
# Threshold of the laplacian to detect rocks edges. It is not zet tied to a physical property.
laplacian_threshold: 100.0
# Resolution of each cell in meters
map_resolution: 0.05
# Size of the map height in meters
map_size_height: 5.0
# Size of the map width in meters
map_size_width: 5.0
# First obstacle dilation iterations
obstacle_iterations: 2
# Kernel size to dilate obstacle first time [cells]
obstacle_kernel_size: 3
# Second obstacle dilation iterations (area surrounding an obstacle)
obstacle_vicinity_iterations: 3
# Kernel size to dilate obstacle second time [cells]
obstacle_vicinity_kernel_size: 3
# in meters, needed for obstacle dilation
robot_size: 0.4
# Obstacles the rover can tolerate when there is no sinkage [m]
rover_obstacle_clearance: 0.12
# Slope the rover can travel in nominal case [rad]
rover_slope_gradeability: 0.262
# How many normal cell a slope map cell will contain
slope_map_scale: 5
