--- name:exoter
# Configuration of Path Tracker parameters, namely distances, velocities and turn radius
ptConfig:
  minTurnRadius: 0.6
  translationalVelocity: 0.02
  rotationalVelocity: 0.05
  corridor: 0.2
  maxDisalignment: 0.15
  lookaheadDistance: 0.50
  backwards: false

pdConfig:
  P: 0.5
  D: 0.375
  saturation: 0.3491

# Default goal heading tolerance (deg).
tolHeading: 3
# Default distance from the goal position tolerance (m).
tolPos:     0.075

repeatCommand: true

--- name:hdpr
# Configuration of Path Tracker parameters, namely distances, velocities and turn radius
ptConfig:
  minTurnRadius: 0.95
  translationalVelocity: 0.2
  rotationalVelocity: 0.15
  corridor: 1.5
#  corridor: 1.0
  maxDisalignment: 1.0
  lookaheadDistance: 4.0
#  lookaheadDistance: 3.0
  backwards: false

pdConfig:
  P: 0.5
  D: 0.025
  saturation: 0.3491

# Set the heading tolerance to 3 degrees
tolHeading: 5
# 50cm is precise enough for HDPR
tolPos:     0.5

repeatCommand: true

--- name:hdpr_autonomy
# Configuration of Path Tracker parameters, namely distances, velocities and turn radius
ptConfig:
  minTurnRadius: 0.95
  translationalVelocity: 0.1
  rotationalVelocity: 0.05
  corridor: 1.5
  maxDisalignment: 1.0
  lookaheadDistance: 4.0
  backwards: false

pdConfig:
  P: 0.5
  D: 0.025
  saturation: 0.3491

# Set the heading tolerance to 3 degrees
tolHeading: 5
# 50cm is precise enough for HDPR
tolPos:     0.5

repeatCommand: true

--- name:hdpr_lab
# Configuration of Path Tracker parameters, namely distances, velocities and turn radius
ptConfig:
  minTurnRadius: 1.10
  translationalVelocity: 0.10
  rotationalVelocity: 0.05
  corridor: 0.5
  maxDisalignment: 0.15
  lookaheadDistance: 1.2
  backwards: false

pdConfig:
  P: 0.5
  D: 0.025
  saturation: 0.3491

# Set the heading tolerance to 3 degrees
tolHeading: 3
# 50cm is precise enough for HDPR
tolPos:     0.25

repeatCommand: true
