--- name:default
# Configuration of Path Tracker parameters, namely distances, velocities and turn radius
ptConfig:
  minTurnRadius: 0.6
  translationalVelocity: 0.08
  rotationalVelocity: 0.2094
  corridor: 0.2
  maxDisalignment: 0.15
  lookaheadDistance: 0.60
  backwards: false

pdConfig:
  P: 0.5
  D: 0.375
  saturation: 0.3491

# Default goal heading tolerance (deg).
tolHeading: 3
# Default distance from the goal position tolerance (m).
tolPos:     0.075

--- name:exoter
# Configuration of Path Tracker parameters, namely distances, velocities and turn radius
ptConfig:
  minTurnRadius: 0.6
  translationalVelocity: 0.05
  rotationalVelocity: 0.15
  corridor: 0.2
  maxDisalignment: 0.15
  lookaheadDistance: 0.50
  backwards: false

--- name:hdpr
# Configuration of Path Tracker parameters, namely distances, velocities and turn radius
ptConfig:
  minTurnRadius: 0.95
  translationalVelocity: 0.4
  rotationalVelocity: 0.15
  corridor: 1.5
  maxDisalignment: 1.0
  lookaheadDistance: 3.5
  backwards: false

pdConfig:
  P: 0.5
  D: 0.025
  saturation: 0.3491

# Do not care about the heading
tolHeading: 360
# 50cm is precise enough for HDPR
tolPos:     0.5
# boolean to choose if output commands should be resend even when they are the same
repeatCommand: true
